language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`

script: make
env:
  - OCAML_VERSION=4.02
os:
  - linux
